logging:
  config: classpath:logback-local.xml

# Runtime mode
pn:
  env:
    runtime: DEVELOPMENT
#pn.env.runtime=PROD

templatesPath: "templates"
templatesImagesPath: "images"
templatesLogo: "aar-logo-short-small.png"

templates:
  notification-received-legal-fact:
    input:
      IT: "NotificationReceivedLegalFact.html"
      DE: "NotificationReceivedLegalFact_de.html"
      SL: "NotificationReceivedLegalFact_sl.html"
      FR: "NotificationReceivedLegalFact_fr.html"
  pecDeliveryWorkflowLegalFact:
    input:
      IT: "PecDeliveryWorkflowLegalFact.html"
      DE: "PecDeliveryWorkflowLegalFact_de.html"
      SL: "PecDeliveryWorkflowLegalFact_sl.html"
      FR: "PecDeliveryWorkflowLegalFact_fr.html"
  notificationViewedLegalFact:
    input:
      IT: "NotificationViewedLegalFact.html"
      DE: "NotificationViewedLegalFact_de.html"
      SL: "NotificationViewedLegalFact_sl.html"
      FR: "NotificationViewedLegalFact_fr.html"
  pdfFileCompliance:
    input:
      IT: "PdfFileCompliance.html"
  pdfLegalFact:
    input:
      IT: "LegalFactMalfunction.html"
      DE: "PdfLegalFact_de.html"
      SL: "PdfLegalFact_sl.html"
      FR: "PdfLegalFact_fr.html"
  notificationCancelledLegalFact:
    input:
      IT: "NotificationCancelledLegalFact.html"
      DE: "NotificationCancelledLegalFact_de.html"
      SL: "NotificationCancelledLegalFact_sl.html"
      FR: "NotificationCancelledLegalFact_fr.html"
  notificationAAR:
    input:
      IT: "NotificationAAR.html"
      DE: "NotificationAAR_de.html"
      SL: "NotificationAAR_sl.html"
      FR: "NotificationAAR_fr.html"
  notificationAAR_RADDalt:
    input:
      IT: "NotificationAAR_RADDalt.html"
      DE: "NotificationAAR_RADDalt_de.html"
      SL: "NotificationAAR_RADDalt_sl.html"
      FR: "NotificationAAR_RADDalt_fr.html"
  analogDeliveryWorkflowFailureLegalFact:
    input:
      IT: "AnalogDeliveryWorkflowFailureLegalFact.html"
      DE: "AnalogDeliveryWorkflowFailureLegalFact_de.html"
      SL: "AnalogDeliveryWorkflowFailureLegalFact_sl.html"
      FR: "AnalogDeliveryWorkflowFailureLegalFact_fr.html"
  notificationAARForEMAIL:
    input:
      IT: "NotificationAARForEMAIL.html"
      DE: "NotificationAARForEMAIL_de.html"
      SL: "NotificationAARForEMAIL_sl.html"
      FR: "NotificationAARForEMAIL_fr.html"
  notificationAARForPEC:
    input:
      IT: "NotificationAARForPEC.html"
      DE: "NotificationAARForPEC_de.html"
      SL: "NotificationAARForPEC_sl.html"
      FR: "NotificationAARForPEC_fr.html"
  notificationAARForSMS:
    input:
      IT: "NotificationAARForSMS.txt"
      SUB: "NotificationAARSubject.txt"
  emailbody:
    input:
      IT: "emailbody.html"
      SUB: "emailsubject.txt"
  pecbody:
    input:
      IT: "pecbody.html"
      SUB: "pecsubject.txt"
  pecbodyconfirm:
    input:
      IT: "pecbodyconfirm.html"
      SUB: "pecsubjectconfirm.txt"
  pecbodyreject:
    input:
      IT: "pecbodyreject.html"
      SUB: "pecsubjectreject.txt"
  smsbody:
    input:
      IT: "smsbody.txt"