logging:
  config: config/logback-local.xml
server:
  port: 8099

pn:
  env: # Runtime mode
    runtime: DEVELOPMENT
  templates-engine:
    parameterStoreCacheTTL: 10m
    urlResolverTimeout: 5s

# AWS specific configurations
aws:
  region-code: us-east-1
  profile-name: ${PN_AWS_PROFILE_NAME:default}
  endpoint-url: http://localhost:4566

templatesPath: "generated-templates-assets/templates"
defaultLanguage: IT
templates:
  notificationReceivedLegalFact:
    input:
      IT: "NotificationReceivedLegalFact/NotificationReceivedLegalFact.html"
      DE: "NotificationReceivedLegalFact/NotificationReceivedLegalFact_de.html"
      SL: "NotificationReceivedLegalFact/NotificationReceivedLegalFact_sl.html"
      FR: "NotificationReceivedLegalFact/NotificationReceivedLegalFact_fr.html"
  pecDeliveryWorkflowLegalFact:
    input:
      IT: "PecDeliveryWorkflowLegalFact/PecDeliveryWorkflowLegalFact.html"
      DE: "PecDeliveryWorkflowLegalFact/PecDeliveryWorkflowLegalFact_de.html"
      SL: "PecDeliveryWorkflowLegalFact/PecDeliveryWorkflowLegalFact_sl.html"
      FR: "PecDeliveryWorkflowLegalFact/PecDeliveryWorkflowLegalFact_fr.html"
  notificationViewedLegalFact:
    input:
      IT: "NotificationViewedLegalFact/NotificationViewedLegalFact.html"
      DE: "NotificationViewedLegalFact/NotificationViewedLegalFact_de.html"
      SL: "NotificationViewedLegalFact/NotificationViewedLegalFact_sl.html"
      FR: "NotificationViewedLegalFact/NotificationViewedLegalFact_fr.html"
  malfunctionLegalFact:
    input:
      IT: "MalfunctionLegalFact/MalfunctionLegalFact.html"
      DE: "MalfunctionLegalFact/MalfunctionLegalFact_de.html"
      SL: "MalfunctionLegalFact/MalfunctionLegalFact_sl.html"
      FR: "MalfunctionLegalFact/MalfunctionLegalFact_fr.html"
  notificationCancelledLegalFact:
    input:
      IT: "NotificationCancelledLegalFact/NotificationCancelledLegalFact.html"
      DE: "NotificationCancelledLegalFact/NotificationCancelledLegalFact_de.html"
      SL: "NotificationCancelledLegalFact/NotificationCancelledLegalFact_sl.html"
      FR: "NotificationCancelledLegalFact/NotificationCancelledLegalFact_fr.html"
  notificationAar:
    input:
      IT: "NotificationAAR/NotificationAAR.html"
      DE: "NotificationAAR/NotificationAAR_de.html"
      SL: "NotificationAAR/NotificationAAR_sl.html"
      FR: "NotificationAAR/NotificationAAR_fr.html"
    resolvers:
      senderLogoBase64:
        enabled: true
        bypassAllWithNull: false
        returnNullOnError: true
        whitelistEnabled: false
#        whitelistParameterStores:
#          - /pn-templates-engine/Whitelist1
#          - /pn-templates-engine/Whitelist2
  notificationAarRaddAlt:
    input:
      IT: "NotificationAAR_RADDalt/NotificationAAR_RADDalt.html"
      DE: "NotificationAAR_RADDalt/NotificationAAR_RADDalt_de.html"
      SL: "NotificationAAR_RADDalt/NotificationAAR_RADDalt_sl.html"
      FR: "NotificationAAR_RADDalt/NotificationAAR_RADDalt_fr.html"
    resolvers:
      senderLogoBase64:
        enabled: true
        bypassAllWithNull: false
        returnNullOnError: true
        whitelistEnabled: false
  analogDeliveryWorkflowFailureLegalFact:
    input:
      IT: "AnalogDeliveryWorkflowFailureLegalFact/AnalogDeliveryWorkflowFailureLegalFact.html"
      DE: "AnalogDeliveryWorkflowFailureLegalFact/AnalogDeliveryWorkflowFailureLegalFact_de.html"
      SL: "AnalogDeliveryWorkflowFailureLegalFact/AnalogDeliveryWorkflowFailureLegalFact_sl.html"
      FR: "AnalogDeliveryWorkflowFailureLegalFact/AnalogDeliveryWorkflowFailureLegalFact_fr.html"
  analogDeliveryWorkflowTimeoutLegalFact:
    input:
      IT: "AnalogDeliveryWorkflowTimeoutLegalFact/AnalogDeliveryWorkflowTimeoutLegalFact.html"
  notificationAarForEmail:
    input:
      IT: "NotificationAARForEMAIL/NotificationAARForEMAIL.html"
      DE: "NotificationAARForEMAIL/NotificationAARForEMAIL_de.html"
      SL: "NotificationAARForEMAIL/NotificationAARForEMAIL_sl.html"
      FR: "NotificationAARForEMAIL/NotificationAARForEMAIL_fr.html"
  notificationAarForPec:
    input:
      IT: "NotificationAARForPEC/NotificationAARForPEC.html"
      DE: "NotificationAARForPEC/NotificationAARForPEC_de.html"
      SL: "NotificationAARForPEC/NotificationAARForPEC_sl.html"
      FR: "NotificationAARForPEC/NotificationAARForPEC_fr.html"
  notificationAarForSms:
    input:
      IT: "NotificationAARForSMS/NotificationAARForSMS.txt"
  notificationAarForSubject:
    input:
      IT: "NotificationAARFor_Subject/NotificationAARFor_Subject.txt"
  mailVerificationCodeBody:
    input:
      IT: "Mail_VerificationCodeBody/Mail_VerificationCodeBody.html"
  pecVerificationCodeBody:
    input:
      IT: "PEC_VerificationCodeBody/PEC_VerificationCodeBody.html"
  pecVerificationCodeSubject:
    loadAsString: true
    input:
      IT: "PEC_VerificationCodeSubject/PEC_VerificationCodeSubject.txt"
  pecValidationContactsSuccessBody:
    input:
      IT: "PEC_ValidationContactsSuccessBody/PEC_ValidationContactsSuccessBody.html"
  pecValidationContactsRejectBody:
    input:
      IT: "PEC_ValidationContactsRejectBody/PEC_ValidationContactsRejectBody.html"
  smsVerificationCodeBody:
    loadAsString: true
    input:
      IT: "SMS_VerificationCodeBody/SMS_VerificationCodeBody.txt"
  mailVerificationCodeSubject:
    loadAsString: true
    input:
      IT: "Mail_VerificationCodeSubject/Mail_VerificationCodeSubject.txt"
  pecValidationContactsSuccessSubject:
    loadAsString: true
    input:
      IT: "PEC_ValidationContactsSuccessSubject/PEC_ValidationContactsSuccessSubject.txt"
  pecValidationContactsRejectSubject:
    loadAsString: true
    input:
      IT: "PEC_ValidationContactsRejectSubject/PEC_ValidationContactsRejectSubject.txt"
  notificationCceForEmail:
    input:
      IT: "NotificationCceForEmail/NotificationCceForEmail.html"
  notificationCceForSubject:
    input:
      IT: "NotificationCceFor_Subject/NotificationCceFor_Subject.txt"