logging:
  config: config/logback-local.xml
server:
  port: 8099

pn:
  env: # Runtime mode
    runtime: DEVELOPMENT

# AWS specific configurations
aws:
  region-code: us-east-1
  profile-name: ${PN_AWS_PROFILE_NAME:default}
  endpoint-url: http://localhost:4566
